[mypy]
python_version = 3.12
warn_unused_configs = True
warn_redundant_casts = True
warn_unused_ignores = False
disallow_untyped_defs = False
check_untyped_defs = True
no_implicit_optional = True
plugins = pydantic.mypy

[mypy-aiogram.*]
ignore_missing_imports = True

[mypy-redis.*]
ignore_missing_imports = True
